#!/usr/bin/env python
import argparse
import os
import shutil

parser = argparse.ArgumentParser()
parser.add_argument('file_name',metavar='file',help='filename or absolute filename')
arguments = parser.parse_args()
argument1_file=arguments.file_name

# checking file is a backup file or source

if ".ba_ck" in argument1_file:
     if "/" in argument1_file:
         if os.path.exists(argument1_file) and os.path.isfile(argument1_file):
             source = argument1_file
             argument1_file=argument1_file[:-6]
             destination = argument1_file
             dest = shutil.copyfile(source, destination)
             print("file {} is created".format(destination))
         else:
             print("File does not exist")
     else:
         cwd = os.getcwd()
         source = os.path.join(cwd, argument1_file)
         if os.path.isfile(source):
             f_name = argument1_file[:-6]
             destination = os.path.join(cwd, f_name)
             dest = shutil.copyfile(source, destination)
             print("file {} is created".format(destination))
         else:
             print("file does not exist")

else:
   if "/" in argument1_file:

     if os.path.exists(argument1_file) and os.path.isfile(argument1_file):
        source=argument1_file
        destination = argument1_file+".ba_ck"
        dest = shutil.copyfile(source, destination)
        print("file {} is created".format( destination))


     else:
        print("file does not exist")

   else:
    cwd = os.getcwd()
    source = os.path.join(cwd, argument1_file)
    if os.path.isfile(source):
        f_name = argument1_file+".ba_ck"
        destination = os.path.join(cwd, f_name)
        dest = shutil.copyfile(source, destination)
        print("file {} is created".format( destination))
    else:
         print("file does not exist")


